### ISSUE TITLE
Powa-web proxy error

### ISSUE THREAD

**Issue by TezkaRabota** [powa-team/powa-web#118] opened 2020-11-25 09:19 UTC
Hi guys,
I have a problem getting  "Details for all queries" for some databases. I get an error message:

"""
An error occured while loading this widget
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /server/18/metrics/database_all_queries/c3_sikkr/.

Reason: Error reading from remote server
"""

Can you please advise me what can cause this problem and how to solve it.

Regards, Domen

**Comment by rjuju** [comment] 2020-11-25 12:28
Hello,

That's an unusual message.  Are you using the UI with an external http daemon, like apache?

**Comment by TezkaRabota** [comment] 2020-11-25 12:33
Yes, I'm using apache http deamon.

 

Best regards!




Domen Šetar
Computer Systems Support
IZUM – Institute of Information Science | Prešernova ulica 17 | 2000 Maribor | Slovenia
T: +386 2 25 20 339 | M: +386 41 676 342 |  <http://www.izum.si/> www.izum.si | domen.setar@izum.si <mailto:domen.setar@izum.si>

**Comment by TezkaRabota** [comment] 2020-11-25 12:35
Best regards!




Domen Šetar
Computer Systems Support
IZUM – Institute of Information Science | Prešernova ulica 17 | 2000 Maribor | Slovenia
T: +386 2 25 20 339 | M: +386 41 676 342 |  <http://www.izum.si/> www.izum.si | domen.setar@izum.si <mailto:domen.setar@izum.si>

**Comment by rjuju** [comment] 2020-11-25 12:38
You're probably missing some configuration on mod_proxy then.  Maybe that database has more rows to be fetched compared to other databases, making the query runs for a longer time, so adding some timeout / keepalive parameter would help.  Note that this isn't due to powa-web, so you might get better answer from people with more apache knowledge than me.

**Comment by rjuju** [comment] 2021-02-06 07:09
I'm closing this issue as I didn't have news for some time.  I hope the problem is fixed, if not and if you still have questions feel frop to reply here or open a new issue.

**Closed by rjuju** 2021-02-06 07:09 UTC
