### ISSUE TITLE
Visible ratio

### ISSUE THREAD

**Issue by anayrat** [powa-team/powa-web#65] opened 2018-11-26 14:45 UTC
Hello,

I have an idea of new feature : compute a kind of visible ratio between relpages and relallvisible to know which table should be vacuumed for Index-only-scan

Regards,

**Comment by rjuju** [comment] 2019-08-10 10:06
It would be nice, but unfortunately, those are counters visible in local database only.  By design, we want to avoid to connect on all databases on a given server when doing a snapshot, so that's something we won't be able to do.  I'm closing this issue as I don't see the per-database object problem being solved any time soon.

**Closed by rjuju** 2019-08-10 10:06 UTC
Labels: enhancement
